<div style="position:absolute; bottom: 0; width: 100%;  height: 3em;  background-color: #FFE97F;z-index: 99;margin:0px 0px;">
<p align=right style="position:relative;top:8px;right:15px;margin:0px 0px;padding:0;"><input type="button" value=" 홈으로 돌아가기 " onclick='window.location="/index.html"' /> 
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 본 사이트는 채경자 강사(maielckj@네이버)의 수강생을 위한 지원 시스템입니다.</p>
</div>